TokoSaya/TokoSaya.Web/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TokoSaya.DataModels;
using TokoSaya.ViewModels;
using TokoSaya.Web.AddOns;

namespace TokoSaya.Web.Controllers
{
    public class CatalogController : Controller
    {
        private readonly DBfirst_TokoSayaContext db;

        public CatalogController(DBfirst_TokoSayaContext _db)
        {
            this.db = _db;
        }

        public int getIdCustomer()
        {
            return Convert.ToInt32(HttpContext.Session.GetInt32("IdCustomer"));
        }

        public async Task<IActionResult> Index(string sortOrder,
                                              string searchString,
                                              string currentFilter,
                                              int? pageNumber,
                                              int? totalProduct,
                                              int? estimatePrice, int? IdCategory)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentSort"] = sortOrder;

            ViewBag.TotalProduct = totalProduct > 0 ? totalProduct : 0;
            ViewBag.EstimatePrice = estimatePrice > 0 ? estimatePrice : 0;
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;


            List<VMProducts> data = Repo.ProductRepo.AllData(db);

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameProduct.ToLower().Contains(searchString.ToLower()))
                                .ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }
            int pageSize = 4;
            ViewBag.CategoryList = await Repo.CategoryRepo.AllData(db);

            return View(data);
            //return View(PaginatedList<VMProducts>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        [HttpPost]
        public IActionResult OrderPreview(List<VMProducts> list, int TotalProduct, int Estimate)
        {
            ViewBag.TotalProduct = TotalProduct;
            ViewBag.Estimate = Estimate;
            return View(list);
        }

        [HttpPost]
        public IActionResult FixOrder(List<VMProducts> list, int TotalProduct, int Estimate)
        {

            VMRespon res = Repo.OrderRepo.Order(db, list, TotalProduct, Estimate, getIdCustomer());
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });
        }

        public IActionResult History()
        {
            List<VMOrderHeaders> data = Repo.OrderRepo.DataHeader(db, getIdCustomer());
            return View(data);
        }

        public IActionResult Detail(int id)
        {
            List<VMOrderHeaders> data = Repo.OrderRepo.DataDetail(db, id);
            VMOrderHeaders dataObj = data.FirstOrDefault();
            ViewBag.DataObj = dataObj;
            return View(data);
        }
    }
}

TokoSaya/TokoSaya.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TokoSaya.DataModels;
using TokoSaya.ViewModels;
using TokoSaya.Web.AddOns;

namespace TokoSaya.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly DBfirst_TokoSayaContext db;
        public CategoryController(DBfirst_TokoSayaContext _db)
        {
            this.db = _db;
        }


        public async Task<IActionResult> Index(string sortOrder,
                                               string searchString,
                                               string currentFilter,
                                               int? pageNumber)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentSort"] = sortOrder;


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;


            List<VMCategory> data = await Repo.CategoryRepo.AllData(db);

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCategory.ToLower().Contains(searchString.ToLower())
                                    || a.Description.ToLower().Contains(searchString.ToLower()))
                                .ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCategory).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCategory).ToList();
                    break;
            }
            int pageSize = 3;

            return View(PaginatedList<VMCategory>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(VMCategory dataParam)
        {
            int? IdCustomer = HttpContext.Session.GetInt32("IdCustomer");
            dataParam.CreateBy = IdCustomer;

            VMRespon res = Repo.CategoryRepo.Create(db, dataParam);
            if (res.isValid)
            {
                //return RedirectToAction("Index");
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            VMCategory data = Repo.CategoryRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(VMCategory dataParam)
        {
            VMRespon res = Repo.CategoryRepo.Edit(db, dataParam);
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });

        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            VMCategory data = Repo.CategoryRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            VMCategory data = Repo.CategoryRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Delete(VMCategory dataParam)
        {
            VMRespon res = Repo.CategoryRepo.Delete(db, dataParam);
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });

            }
            return Json(new { status = "failed", data = res });
            ;
        }
    }
}

TokoSaya/TokoSaya.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TokoSaya.DataModels;
using TokoSaya.ViewModels;
using TokoSaya.Web.AddOns;

namespace TokoSaya.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly DBfirst_TokoSayaContext db;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductController(DBfirst_TokoSayaContext _db, IWebHostEnvironment hostEnvironment)
        {
            this.db = _db;
            this.webHostEnvironment = hostEnvironment;
        }
        public IActionResult Index(string sortOrder,
                                               string searchString,
                                               string currentFilter,
                                               int? pageNumber)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentSort"] = sortOrder;


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;


            List<VMProducts> data = Repo.ProductRepo.AllData(db);

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameProduct.ToLower().Contains(searchString.ToLower()))
                                .ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }
            int pageSize = 3;

            return View(PaginatedList<VMProducts>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            List<VMVariants> listVariant = new List<VMVariants>();
            List<VMCategory> listCategory = await Repo.CategoryRepo.AllData(db);
            ViewBag.ListCategory = listCategory;
            ViewBag.ListVariant = listVariant;

            VMProducts data = new VMProducts();

            return View(data);
        }

        [HttpPost]
        public IActionResult Create(VMProducts dataParam)
        {
            string uniqueFileName = UploadedFile(dataParam);
            dataParam.Image = uniqueFileName;

            VMRespon res = Repo.ProductRepo.Create(db, dataParam);
            if (res.isValid)
            {
                //return RedirectToAction("Index");
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            VMProducts data = Repo.ProductRepo.GetDataById(db, id);


            List<VMVariants> listVariant = Repo.VariantRepo.DataVariantByIdCategory(db, data.IdCategory);
            List<VMCategory> listCategory = await Repo.CategoryRepo.AllData(db);
            ViewBag.ListCategory = listCategory;
            ViewBag.ListVariant = listVariant;

            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(VMProducts dataParam)
        {
            string uniqueFileName = UploadedFile(dataParam);
            dataParam.Image = uniqueFileName;

            VMRespon res = Repo.ProductRepo.Edit(db, dataParam);
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });

        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            VMProducts data = Repo.ProductRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            VMProducts data = Repo.ProductRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Delete(VMProducts dataParam)
        {
            VMRespon res = Repo.ProductRepo.Delete(db, dataParam);
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });

            }
            return Json(new { status = "failed", data = res });
            
        }

        public JsonResult DataVariantAjax(int id)
        {
            List<VMVariants> list = Repo.VariantRepo.DataVariantByIdCategory(db, id);
            return Json(list);
        }

        private string UploadedFile(VMProducts model)
        {
            string uniqueFileName = null;

            if (model.ImageFile != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ImageFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

TokoSaya/TokoSaya.Web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TokoSaya.DataModels;
using TokoSaya.ViewModels;
using TokoSaya.Web.AddOns;

namespace TokoSaya.Web.Controllers
{
    public class VariantController : Controller
    {
        private readonly DBfirst_TokoSayaContext db;
        public VariantController(DBfirst_TokoSayaContext _db)
        {
            this.db = _db;
        }
        public IActionResult Index(string sortOrder,
                                               string searchString,
                                               string currentFilter,
                                               int? pageNumber)
        {
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["CurrentSort"] = sortOrder;


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;


            List<VMVariants> data = Repo.VariantRepo.AllData(db);

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                                    || a.Description.ToLower().Contains(searchString.ToLower()))
                                .ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }
            int pageSize = 3;

            return View(PaginatedList<VMVariants>.CreateAsync(data, pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            List<VMCategory> listCategory = await Repo.CategoryRepo.AllData(db);
            ViewBag.ListCategory = listCategory;
            return View();
        }

        [HttpPost]
        public IActionResult Create(VMVariants dataParam)
        {
            VMRespon res = Repo.VariantRepo.Create(db, dataParam);
            if (res.isValid)
            {
                //return RedirectToAction("Index");
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            VMVariants data = Repo.VariantRepo.GetDataById(db, id);
            List<VMCategory> listCategory = await Repo.CategoryRepo.AllData(db);
            ViewBag.ListCategory = listCategory;

            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(VMVariants dataParam)
        {
            VMRespon res = Repo.VariantRepo.Edit(db, dataParam);
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });
            }
            return Json(new { status = "failed", data = res });

        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            VMVariants data = Repo.VariantRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            VMVariants data = Repo.VariantRepo.GetDataById(db, id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Delete(VMVariants dataParam)
        {
            VMRespon res = Repo.VariantRepo.Delete(db, dataParam);
            if (res.isValid)
            {
                return Json(new { status = "success", data = res });

            }
            return Json(new { status = "failed", data = res });
            ;
        }
    }
}

TokoSaya/TokoSaya.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<style>
    .img-responsive {
        width: auto;
        height: 180px;
    }
</style>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TokoSaya</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@

    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/assets/images/favicon.png">
    <!-- Custom CSS -->
    <link href="~/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/assets/dist/css/style.min.css" rel="stylesheet">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>

<body>
 @*   <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>*@

    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")


        <div class="page-wrapper">
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-7 align-self-center">
                        <h3 class="page-title text-truncate text-dark font-weight-medium mb-1">Good Morning Jason!</h3>
                        <div class="d-flex align-items-center">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb m-0 p-0">
                                    <li class="breadcrumb-item">
                                        <a href="index.html">Dashboard</a>
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <div class="col-5 align-self-center">
                        <div class="customize-input float-right">
                            <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                                <option selected>Aug 19</option>
                                <option value="1">July 19</option>
                                <option value="2">Jun 19</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid">
                @RenderBody()
            </div>

            <footer class="footer text-center text-muted">
                Tokosaya <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>
        </div>


    </div>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/assets/dist/js/app-style-switcher.js"></script>
    <script src="~/assets/dist/js/feather.min.js"></script>
    <script src="~/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/assets/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/assets/dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="~/assets/extra-libs/c3/d3.min.js"></script>
    <script src="~/assets/extra-libs/c3/c3.min.js"></script>
    <script src="~/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/assets/dist/js/pages/dashboards/dashboard1.min.js"></script>

    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)*@
</body>
</html>

TokoSaya/TokoSaya.Web/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Http
@{
    var IdRole = Context.Session.GetInt32("IdRole");
}
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Home"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Home</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                @if (IdRole == 1)
                {
                    <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="Index" asp-controller="Category"
                           aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                                Category
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Variant"
                           aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">
                                Variant
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Product"
                           aria-expanded="false">
                            <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">
                                Product
                            </span>
                        </a>
                    </li>
                }
                @if (IdRole == 1 || IdRole == 2)
                {
                    <li class="list-divider"></li>
                    <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="Index" asp-controller="Catalog"
                           aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                                Catalog
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="History" asp-controller="Catalog"
                           aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                                History
                            </span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->